name: Churn ML Pipeline

on:
  push:
    branches: 
      - cicd
    paths-ignore:
      - '**/*.md'
      - 'k8s/**'


env:
  AWS_REGION: us-east-1
  S3_BUCKET: tad-churn-datasets
  MLFLOW_TRACKING_URI: "http://54.166.215.199:5000"

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Python
        uses: actions/setup-python@v6 
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: | 
          pip install -r requirements.txt

      - name: Generate dataset
        run: python3 generate_data.py

      - name: Configure AWS Credentainls
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Access
        run: |
          aws sts get-caller-identity
          env | grep AWS || true

      - name: Train Model
        run: python3 train.py
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}

      - name: Push model to S3 directly
        run: |
          aws s3 cp models/churn_model.pkl s3://tad-churn-datasets/models/churn_model.pkl
          echo "Model pushed to S3 is success"

      - name: Update inference.yaml with S3 model path
        run: |
          MODEL_URI="s3://churn-model-bucket-cicd-abhi/models/churn_model.pkl"
          sed -i "s|storageUri: .*|storageUri: $MODEL_URI|g" k8s/inference.yaml
      
      - name: Commit updated inference.yaml
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add k8s/inference.yaml
          git commit -m "Update model S3 path [skip ci]" || echo "No changes"
          git push || echo "No changes to push"